### ISSUE TITLE
Question on converting string into numeric format

### ISSUE THREAD

**Issue by MC1978** [Ideolys/carbone#13]
Hi,
I have some problems in converting a numeric result into a real number in excel.

I have seen that the Carbon documentation reports several Formatters for date and string but not for numbers.
Do you know if there is something like convInt, confFloat I could sue in my template?

Thank you in advance for your help,
Best Regards,
Mario

**Comment by devSwoop** [comment]
Hi,
it would be a great improvement, we will work on it :smiley:

**Comment by mahdi-akbary** [comment]
Hi,
I have the same issue, even though I tried to add new formatter my self in the carbon/formatters/number.js
parseN() using parseInt() but it didn't work, and now I think when the data is being written into xml and it's after the formatters and even getBuilderFunction() obviously that's being inserted as string.
guys I really need to have my data as number in .ods file because the charts being generated by them will not show my properly because it's complaining that I have to convert the string to number to show the chart.
Please show me a solution or a work around

**Comment by exolab** [comment]
@mahdi-akbary Since nothing seems to be happening with this issue: have you tried putting a cell next to your data that converts the text? Something like this...

`=VALUE(A1)`

It's not a good solution, but it sort of works.

**Comment by mahdi-akbary** [comment]
@exolab that is a smart solution since nothing happens here but I fixed the issue and made a new npm package with this link: https://www.npmjs.com/package/api-report-generator

**Comment by dgrelaud** [comment]
Thank you @mahdi-akbary . Please, could you open a pull request?

**Comment by steevepay** [comment]
It's an important issue, we are testing some possibilities to fix the numeric conversion. Hold on we are coming back to you!

**Comment by paolobrasolin** [comment]
I dug a bit into this.

From https://www.loc.gov/preservation/digital/formats/fdd/fdd000439.shtml:

> <table:table> -- contains a series of <table:table-column> elements to describe each column in the table. The column specifications are followed by <table:table-row> elements consisting of <table:table-cell> entries. A cell that contains a string will contain a child <text:p> element. **A cell containing a number will also contain a <text:p> that shows the display form of the value. The actual value is stored in the <table:table-cell> element using two attributes: office:value-type and office:value. Numeric value types for cells are float, percentage, and currency.** Separate types are used to indicate date and time values. For discussion of cells containing formulas, see Notes below -- </table:table>

In the template, a cell containing some interpolated value is

```xml
<table:table-cell office:value-type="string" calcext:value-type="string">
  <text:p>{d.cars[i+1].price}</text:p>
</table:table-cell>
```

and the desired output is something like

```xml
<table:table-cell office:value-type="float" office:value="123" calcext:value-type="float">
  <text:p>123</text:p>
</table:table-cell>
```

**Problem 1**: I see no obvious way to force the `value-type` from the editor.
**Problem 2**: `carbone` is just interpolating the contents of the `text:p` tag but we need to change the value of the `office:value` attribute too as the quotation above dictates.

This a blocking issue at my job; since using `carbone` would spare me a huge amount of headaches I'm definitely willing to put some work into properly fixing it. I've skimmed the code but I'm a bit confused; any pointer would be immensely helpful @devSwoop @dgrelaud

**Comment by Dobby85** [comment]
This bug is already resolved in our side. We are currently resolving bugs and we will update evrything in the version 2 of Carbone which will be released in 1 ou 2 week. We are coming back to you when it will be done!

**Comment by steevepay** [comment]
Hi, the fix is available on the next version of Carbone. Set the formatter `:formatN` and it will convert the number as real number on the XLSX document. Then you can perform a calculation or even create charts (if some condition are met).
Check out the [v2 branch](https://github.com/Ideolys/carbone/tree/v2.0) or NPM: `npm install carbone@2.0.0-beta.0`
[The changes with examples are available here](https://github.com/Ideolys/carbone/blob/v2.0/CHANGELOG.md).

**Comment by steevepay** [comment]
The fix has been published on master https://github.com/Ideolys/carbone/releases/tag/2.0.0

**Comment by mazero** [comment]
Hello,

I have the same problem. I want to have numeric cells for example on Excel with my data injection but all the data is considered as a string format.

Have you found a solution? Thx 
I'm with the last version of carbone and on Excel.
