### ISSUE TITLE
Malformed JSON in payload

### ISSUE THREAD

**Issue by willemevenwel** [Ideolys/carbone#28]
Hi,

Thanks for a great product! (I have spoken to @devSwoop about this over the chat support, and he has assisted)

When using the API to render a report: [https://app.carbone.io/version/{template uuid}/render]

The logical payload for json would be:
```
{
	"convertTo"   : "pdf",
	"data"        :  {},
  	"complement"  : {},
  	"enum"        : {}
}
```

However this returns and unexpected error:
```
{
"success": false,
"message": "Wrong JSON data",
"data":{},
"errors":[]
}
```

The json node value assigned to either data, complement, enum needs to be **escaped** thus like this:
```
{
	"convertTo"   : "pdf",
	"data"        :  "{\"dog\":\"jack russel\"}",
  	"complement"  : "{}",
  	"enum"        : "{}"
}
```

You can easily escape values for json node values here: [https://www.freeformatter.com/json-escape.html]

So there is a work around, its just not ideal. The only reason why I think this might have been implemented this way, is to allow data to be in a xml/csv format. If not, I think it needs to be corrected.

Regards,

Willem

**Comment by willemevenwel** [comment]
@devSwoop, has this been resolved?

**Comment by devSwoop** [comment]
Well, sending stringified JSON manually is not very handy when you're doing it by your own, but the API is supposed to be called programmatically, and in that case it's not complicated.  
Also, we are working on a new version of the Studio and this API will be rewritten (and more, but I won't spoil you more).  
I am closing it because we won't change the current API and the next one will accept pure JSON object, as mentioned in your original post :wink:

**Comment by willemevenwel** [comment]
Fantastic! Tx
