### ISSUE TITLE
How to Use ifContain Dynamically?

### ISSUE THREAD

**Issue by BharathDachepalli** [Ideolys/carbone#36]
Hi guys, I've been struck from past few days. Actually For text replacement I'm Using :ifContain for example : **{d.j1.INITIATOR.afterTypeACleaning3.18WipeThePartsWith70Ipa:ifContain(satisfactory✔, ✓):ifContain(no,X)}** Here I'm replacing text with ✓ if it exists **satisfactory✔** . Like the way now I had a requirement that if the text contains **satisfactory✔** then I should map another Key else remain same.This is what I'm Trying **{d.j1.INITIATOR.ensureThatStatusLabelIsUpdatedAsToBeCleaned:ifContain(S,({d.j1.USER[key="ensureThatStatusLabelIsUpdatedAsToBeCleaned"].commitedUser}))}** .Where I'm doing wrong?Please throw some light. Does carbone support this kind of thing?

**Comment by devSwoop** [comment]
Hi,

I think you're trying to do too much things.  
First, Carbone does not handle nested markers like this:
> `{d.j1.INITIATOR.ensureThatStatusLabelIsUpdatedAsToBeCleaned:ifContain(S,({d.j1.USER[key="ensureThatStatusLabelIsUpdatedAsToBeCleaned"].commitedUser}))}`

The mistake you make is expecting Carbone to compute things for you while you can do it by your own before calling Carbone. This is a really common mistake, you just have to modify the code which builds your data in order to put what you really want to render inside the Json.
