### ISSUE TITLE
While repetition with arrays, the data gets printed one extra time. That means loop happens for data.length + 1 times.

### ISSUE THREAD

**Issue by PrashanthGowda** [Ideolys/carbone#43]
I have an array of JSON objects as below,

```
const data = [
  {"fname": "Prashanth", "lname": "Gowda"},
  {"fname": "Jonny", "lname": "Doe"},
  {"fname": "Jimmy", "lname": "Doe"}
]
```

and doc template code as below,

```
sentence is having first name {d[i].fname}
sentence is having last name {d[i].lname}

sentence is having first name{d[i+1].fname}
sentence is having last name {d[i+1].lname}
```
when i get the output document it prints one extra line as shown in figure below,

![CaptureCarboneIssue](https://user-images.githubusercontent.com/17117648/62349770-5a4aab00-b51e-11e9-9dff-f2aed32ee065.PNG)

**Comment by PrashanthGowda** [comment]
+1

**Comment by dgrelaud** [comment]
Sorry for the delay to answer...

Yes, it is a side effect of the algorithm. I think I could find a solution in the future.

Meanwhile, you can avoid repeating the "i+1" row entirely. It works and I recommend this syntax as it is less repetitive:

```
sentence is having first name {d[i].fname}
sentence is having last name {d[i].lname}

sentence is having first name{d[i+1].fname}
```

Why? when Carbone finds the first occurence of "i+1 row", it stops searching (the bug is here). It eliminates the i+1 row (but not completely) and it captures the "i" row to repeat it. In a spreadsheet document, it works better because it is easier to find where the i+1 row ends.
I've never fixed this bug as it is not mandatory to write "i+1" row entirely.
I should improve the documentation about that.

Let me know if is is ok for you

David.

**Comment by PrashanthGowda** [comment]
@dgrelaud Thanks this solution works :slightly_smiling_face:
