### ISSUE TITLE
A renderBinary function ?

### ISSUE THREAD

**Issue by praneethmendu** [Ideolys/carbone#62]
Is there a way to send pass a binary instead of a path or XML. I am working on a server that fetches templates from S3 for the sole reason of putting them through carbone. Am I missing something (I am currently writing and reading the template file)? Is there a way to do this? If not would you be interested in merging a new function: renderBinary? I could work on it shouldn't be too difficult.

**Comment by steevepay** [comment]
Hello @praneethmendu,

It does not exist and it is a good feature idea to accept a binary as a parameter of the render function. Create a `renderBinary` is not necessary and it can be handled into the `render` function. As you said, It should not be too difficult. We keep the idea for future Carbone versions because we are currently working on other priorities.
Feel free to fork Carbone and contribute through a pull request! :)

**Comment by praneethmendu** [comment]
Thanks for the reply. I will be trying out a fork
