### ISSUE TITLE
[Feature Request]: Two or more variables inside formatters call

### ISSUE THREAD

**Issue by Alexpelillo** [Ideolys/carbone#65]
**Problem to solve**
Please, I want the ability to write a formatter like a compare function, which I enter two of my aliases (currently you can only enter ONE alias which is data) and return a simple compare and return function.

I'm trying to make it with MS Word or LibreOffice Writer's "IF" Functions but they don't work at all.

**Comment by steevepay** [comment]
Hello @Alexpelillo,
It is not possible yet to pass variables as parameters to a formatter. It is on our 2020 roadmap, I can't tell you yet a specific date. I'm going to set the priority higher for this feature due to the increasing demand ^^.
If you can't wait, feel free to fork and contribute :)
Thanks for you message!

**Comment by steevepay** [comment]
Hi @Alexpelillo, Carbone accepts dynamic variables in all formatters! Carbone passes data to formatters if parameters start with a dot `.` and is not surrounded by quotes, example: `{d.subObject.qtyB:add(.qtyC)}`. For the moment, the website documentation is not up to date, check out the changelog with the examples: [Changelog](https://github.com/Ideolys/carbone/blob/v2.0/CHANGELOG.md)
It is only a beta and available on the [v2 branch](https://github.com/Ideolys/carbone/tree/v2.0) or NPM: `npm install carbone@2.0.0-beta.0`

**Comment by steevepay** [comment]
The feature has been published on master.
