### ISSUE TITLE
[Bug Report]: Base 64 not working ?

### ISSUE THREAD

**Issue by ieltxualganaras** [Ideolys/carbone#66]
**Environment**
Carbone Version: [e.g. Node 8.16.1]
Node Version: [e.g. chrome 22]
Browsers: [e.g. chrome 22]
Desktop OS: [e.g. Ubuntu 18, Mac Os, ...]

**Expected Behaviour**
Base 64 images work as public link images when defining them as explained in the documentation example for base 64 images

**Actual Behaviour**
Exported .odt and .pdf does not replace the image with base64 data

**Steps to reproduce**
Steps to reproduce the bug:
1. Follow the example for base 64 images on the documentation
2. Generate a report
3. Images is not shown in the generated reports

**Comment by steevepay** [comment]
Hello @ieltxualganaras,
We are aware of the issue and a new version of Carbone is coming in few days with a lot of fix and improvements about the base64 image support. I will notify you when it is published :)

**Comment by steevepay** [comment]
Until then, we can find a solution, can you tell me if:
- have you inserted a temporary picture in your template ?
- have you wrote the base64 marker in the alternative text of the picture?

You can follow this: https://carbone.io/documentation.html#public-url-picture
Then, instead of inserting an URL, you can replace with the base64 marker.
The documentation is not really explaining a lot about injecting base64 pictures. An update of the documentation is also coming!
