### ISSUE TITLE
[Feature Request]:  Available for windows

### ISSUE THREAD

**Issue by Rick9595** [Ideolys/carbone#72]
When carbone will be available for windows systems? 
I can use it but i'm not able to convert in pdf. I always get the message "Cannot find LibreOffice. Document conversion cannot be used" even if LibreOffice is correctly installed and usable with UI.
Thank you

**Comment by loneil** [comment]
My team has been using Carbone in our product and have gotten the PDF generation working on our local builds on Windows, needed to alter the install path due to a pending bug in Carbone.
Needed to include the version number in the path or the regex Carbone uses fails (and newer versions of Libre don't include the version# in the path)
`C:\Program Files\LibreOffice 6.3` is what I have.


see this PR for relevant info.
https://github.com/Ideolys/carbone/pull/52

**Comment by Rick9595** [comment]
By changing the name of the folder I'm now able to convert files. Thank you for your support
