### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by sebastian-schlecht** [Ideolys/carbone#8]
Hey,

great work here. I wonder if images are on the roadmap for this project? If yes, are there any plans yet for when this is going to be implemented? I'd love to be able to insert images dynamically into Word templates.

**Comment by dgrelaud** [comment]
Thank you.

In fact, It is already done internally (for MS Word ans LibreOffice), but not Production Ready.
Normally, this feature will not be free, and only available in the SaaS version (currently in development). But it can change... I hesitate.

**Comment by sebastian-schlecht** [comment]
Hey David, thanks for the response. Sadly this forced us to move to a different solution since images were mandatory for us. I‘ll monitor your progress on the managed solution though as it might come in handy for us at a later stage.

**Comment by smbatpetrosyan** [comment]
@sebastian-schlecht Could you please share with "different solution" you found? I'm struggling with the same problem. Thanks.

**Comment by ventr1x** [comment]
It should be pretty easily doable. I mean you could simply implement embedded/base64 images.
Integrating that as a paid feature.. in an open source software?
There is not even ANY mention about a coming paid version that locks basic necessities like images behind a paywall. 
Even if I'd pay for it, I wouldn't necessarily want this solution to be hosted by you.
I for example would need something like this in a local and/or embedded environment to, for example, generate invoices.
That instantly put me off to ever even try this. Thanks for this issue, saved me tons of time.

**Comment by joelgiaufer** [comment]
@dgrelaud have you make a choice regarding images ? 
I'm interested in your project but I need to embed images as url and for now it's a show stopper for me.
Merci d'avance

**Comment by Matzu89** [comment]
@dgrelaud how are you doing on this topic?

**Comment by willemevenwel** [comment]
This is already in production at the hosted solution: https://app.carbone.io/
(and I can confirm its working dynamically and well)

Here are the docs: https://carbone.io/designer-documentation.html#dynamic-pictures-coming-soon-

Just bind the url of the image in your json to the alt text attribute of the image in your document.

**Comment by sguilly** [comment]
@dgrelaud, i need to make a choice between your solution and pdfgeneratorapi.com (paid solution).

As i understand, Dynamic image is only available in your paid version.

Could you give us preview plan prices ?

/BR

**Comment by samuelpetroline** [comment]
Is Base64 images embedding available?

**Comment by devSwoop** [comment]
We've developed it but this is not available yet (too early). We may publish it in the Studio next month :wink:

**Comment by mickeyjohn** [comment]
> This is already in production at the hosted solution: https://app.carbone.io/
> (and I can confirm its working dynamically and well)
> 
> Here are the docs: https://carbone.io/designer-documentation.html#dynamic-pictures-coming-soon-
> 
> Just bind the url of the image in your json to the alt text attribute of the image in your document.

@willemevenwel: for dynamically adding image. Is it available now for the current renderer API? 
Missing this feature is also a stopper for me. 
Thanks.

**Comment by devSwoop** [comment]
@mickeyjohn Yes it is :wink:

**Comment by mickeyjohn** [comment]
@willemevenwel Thanks for your prompt response. Is this feature available in the community version of the API? Thanks.

**Comment by devSwoop** [comment]
This is only available through the web API, with the [Studio](https://app.carbone.io). This won't be published on GitHub but this will *always* be in the free plan.  
Note that this is not stable *yet* but we already have improved it (not published, still testing out).

**Comment by paolog22** [comment]
+1 dynamic image please

**Comment by set-webmaster** [comment]
> This won't be published on GitHub but this will **_always_ be in the free plan**.

Yet.... 
![image](https://user-images.githubusercontent.com/47327415/66053981-4bbe4700-e501-11e9-9981-e1dc9712cc22.png)

**Comment by set-webmaster** [comment]
This missing feature is also a deal breaker for us sadly.

**Comment by dgrelaud** [comment]
Dynamic image is stable and available right now in the new Carbone Render API  and new Carbone Studio : https://studio.carbone.io

You can include image by [URL](https://carbone.io/documentation.html#dynamic-pictures-carbone-render-only-) or [base64](https://carbone.io/documentation.html#base64-picture-in-data)

_Please, avoid using the old studio : https://app.carbone.io_ 

> This missing feature is also a deal breaker for us sadly.

What do you mean?
- Do you want an on-premise version with dynamic image support?
- Do you think it is not stable enough? Please, let me know if we can improve it here or at support@carbone.io

Thank you.

**Comment by set-webmaster** [comment]
Personally I meant that the fact it's missing in the community/open source version is a deal breaker, not that it was completely unavailable as I read comments above and understood it was effectively available in the hosted version.

**Comment by dgrelaud** [comment]
Thank you for your message. Your point of view is interesting.
It is really hard to choose what to put in the Open Source version and what to keep in the Premium solution.

**Comment by set-webmaster** [comment]
I completely understand and I leave it to you to decide and I respect your decision. It just won't be my chosen tool for the task because of crucial missing features (in my own opinion always). 

As for my example above (for barcode generation), maybe an option would be to add the dynamic image in the open source version and keep the barcode generation in the premium version? This way, if people are willing to implement their own barcode generator (or use other open source tools available such as ZXing), then it wouldn't be a complete show stopper for them?

To me, you could also use a model in which all features are free/open source until the user/company using the tool makes a good revenue which justifies paying for the tools they use to generate this revenue (same model as Syncfusion for example, for which all controls, including .docx generation tools, are free until the user/company has a revenue > 1 million $ annually). I don't say 1 million $/year is the optimal target, but you get the point :) I understand that this may raise concerns as to user's honesty regarding their revenues, but in my opinion, it shouldn't affect the final outcome that much. 

Thanks for taking the comment into consideration and have a great day!

**Comment by dgrelaud** [comment]
Thank you for your ideas ;).
We are still young in this market. All feedbacks are interesting.

Open source does not mean necessarily free of charge?
Would you be ready to pay to allow you to use the image feature for commercial use? By default,  the image support feature could be Open Source but not allowed for commercial use for example.

_I closed the issue but we can still argue about adding image support in the Open Source version_

**Comment by set-webmaster** [comment]
I wouldn't consider it as _arguing_ as I'm not trying to convince you of anything here hehe :P I'm just trying to mention my point of view, which you can share, or not, it's completely up to you. But yes I'm open for _discussion_

> Open source does not mean necessarily free of charge?
Is that a question or a declaration? To me, open source does effectively not always mean free of charge. Again, the Syncfusion example applies, all their controls code can be found in their Github repository. Yet they charge any user who use these controls and have a revenue >  1 million $ annually. 

As to your other question, would I be willing to pay for the image feature for commercial use. Yes certainly, provided the tool is used for commercial purpose, it could effectively be a paid feature. I like your idea of including it in the "free tier" of the hosted version, but 100 reports/month does not sound that **generous** to me (again, our opinions might differ and I completely understand it )

**Comment by set-webmaster** [comment]
Maybe this would be a good discussion to have with others to gather more point of views on the question? (depending on your level of interest in updating your business model or not)

**Comment by canercak** [comment]
It's a nice solution and well documented but why open source it if it won't have images? 9 out of my 10 reports use images and that should be the case for 90% of people. I mean wtf, I need logo in every one of reports and I can't have that in open source version? I have a budget to buy a report generator but I will never ever buy this one because because I won't bother implementing it to see how it works. I will go and find another solution. I will see how my reports look like in that solution and I will buy it if my reports work well or if I want them to host it. This is how potential customer thinks.

**Comment by exzizt** [comment]
I would just like to add a kind nudge that it would be amazing if the free version did allow for dynamic image replacement. 😄

**Comment by pdittaro** [comment]
Another vote for dynamic image replacement in the community version, seems strange to not include it.

**Comment by ntodorov** [comment]
@dgrelaud I believe keeping images (and dynamic colouring) only as a paid version is killing your business.
My points are those:
 - you want as many users of the community version as you can get - this will make the carbon npm package very popular.
 - some of those users will not want to host a server for them selfs, many enterprises are like that, so they will start using your SaaS.
 - many of them will even prefer your premium version - the studio because it saves them time - for designing, hosting everything.

I know you probably consider models like ElasticSearch - free if you configure it but there are companies that can SaaS it for you.
Kafka and Confluent - Kafka is free with all of its features, but if you want SaaS - go to Confluent cloud. They will save you all hassle of configuring, packing, upgrading. They also build new support tools around Kafka, for admin, data, and they work their SaaS to be multy cloud, etc - but the main tool is completely free with all of its features.

You have to have huge adoption to expect a percentage of those users to become paid customers (and make you rich - you deserve it! ). Don't be cheap on features give them for free, but get paid for providing another type of value - support, SaaS, UI builder, etc.

**Just my opinion, because you have great potential!**

I was highly hopeful that we can use Carbon but this image feature locket to your hosted version may block me ... security considerations around sending the data, latency, etc.
I was seeing it as building our own and hosting it ourselves in the start and when this is adopted, I'm pretty sure soon there would be a drive for someone to host it for us and saves us the cost of upgrading, patching, etc.
Now I may not have a chance even to implement a PoC ...

Well, wish you luck! It is a great tool, with not so great business model ...

**Comment by RobotCaleb** [comment]
We are evaluating this for commercial purposes and am 100% not going to send our data to your servers in order to generate reports. We are more than happy to pay for a license to use this tool on our infrastructure if it meets our needs, but it absolutely has to include image support. So far I'm impressed, but need image support. Can we talk licensing?

**Comment by RobotCaleb** [comment]
In the meantime may investigate effort involved in adding support for our uses case locally.

**Comment by dantio** [comment]
Any updates if dynamic images will be supported in the open source version? 
It would be great to have this feature.

**Comment by dantio** [comment]
Actually, it's not even complicated. I have build my own carbone docker image that replace the images. Checkout https://github.com/dantio/carbone-docker
I still would appreciate to have it officially supported.

**Comment by panchicore** [comment]
hi community, take a look at this fork list, many of them implement support for images.

https://gist.github.com/panchicore/3136f8d622ff5dc6df9684f7be1ee117

**Comment by panchicore** [comment]
Update 2: This one works best: [ak1dos/carbone](https://github.com/ak1dos/carbone) with the image file path and base64 encoded string, it won't work with URLs yet, I had to submit a PR with a bugfix https://github.com/ak1dos/carbone/pull/1

**Comment by dgrelaud** [comment]
Hello,

- Do you know you can install Carbone with unlimited battle-tested features, report volume, servers [...] in your infrastructure with the On-Premise version? Price starts at 1600Euros/year for startups with SLA support/updates for a 5-year contract. This price is extremely low. It is the roughly the price of 3 days of a freelance developer.

- If yes, why are you spending time creating and maintaining a fork for images? Is the On-Premise solution too expensive? Do you prefer to have a node module version will all features but without studio and without SLA support at a lower price?

Thank you for answer :)

**Comment by panchicore** [comment]
Thank you for jumping in @dgrelaud with that piece of data which is key to taking a decision, as a developer I suggest going all-in and better using the paid service. As an entrepreneur, I will gather some data and will let you know, because your points seem to be very valid, but at the same time money is not easy these days.

**Comment by steinlon** [comment]
> Update 2: This one works best: [ak1dos/carbone](https://github.com/ak1dos/carbone) with the image file path and base64 encoded string, it won't work with URLs yet, I had to submit a PR with a bugfix [ak1dos#1](https://github.com/ak1dos/carbone/pull/1)

hi, how to use the image placeholder in the document pls? Add the base64 string to alt text of image does not work in MS. 
Is it working for you?

**Comment by littleseven007** [comment]
You can use my code to implement this feature! [https://github.com/littleseven007/carbone](url)

**Comment by freddyyeddy** [comment]
I agree that this is a fundamental feature that without it I cant get buy in from corporate as I cant even put together a proof of concept with our data. Without it my companies push back will be "We already have SSRS and it does images".

**Comment by freddyyeddy** [comment]
The issue is that I need to demonstrate the viability of the product before our corporate IT department will allow account creation, as they would need to manage the account, not me. This creates a cart-before-the-horse problem for us. I support compensating for a SaaS solution, but the essence of open source is to gain broader buy in from lower level developers, facilitate rapid turnaround from community resources, and prove utility and viability through this process. Larger corporate users then support the open-source utility when their developers advocate for its use at scale. The sale of the product should be driven by word of mouth from developers who implement your solution, not through gatekeeping features. I am reluctant to advocate for a product that does not align with my principles and standards regarding code and development practices. While it makes sense to reserve the newest version and its features, the key is that they are reserved, not permanently blocked. Purposefully de-featuring your product to drive sales is antithetical to that. Your open-source approach gives you an advantage over companies like Apple and Adobe but but you are aligned in your gatekeeping ideology. We will have to keep using SSRS and MSSQL until I find another viable replacement.

**Comment by kkarpe-dm** [comment]
> Update 1: I took a look at the forks, and the following seems to have this image support: (ordered by my common sense)
> 
> https://github.com/ak1dos/carbone [test 0] https://github.com/Enfexia/carbone [test 1] https://github.com/alvaro-mq/carbone [test 2] https://github.com/rishikeshjoshi/carbone [test 98 no pdf] https://github.com/keeps/carbone [test 99]

@littleseven007 @panchicore  Can you guide on the docker compose/ how to install any of these via Docker? Image replacement is crucial on my end

@dgrelaud he reason for open-sourcing this is privacy not an issue of pricing

e.g Transaction receipts with QR codes can't sit on another server
